-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- proyecto base de datos --
-- by gershwin gil --
CREATE TABLE IF NOT EXISTS colegio.docentes
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    apellido character varying(100) COLLATE pg_catalog."default",
    especialidad character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT docentes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS colegio.matricula
(
    id serial NOT NULL,
    estudiantes_id integer,
    materias_id integer,
    docentes_id integer,
    fecha_matricula date,
    CONSTRAINT matricula_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS colegio.estudiantes
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    apellido character varying(100) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    genero character varying(100) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    CONSTRAINT estudiantes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS colegio.materias
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    descripcion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT materias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS colegio.notas
(
    id integer NOT NULL DEFAULT nextval('colegio.grado_id_seq'::regclass),
    nota numeric(10, 0),
    observaciones character varying(100) COLLATE pg_catalog."default",
    materias_id integer,
    CONSTRAINT grado_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS colegio.matricula
    ADD CONSTRAINT matricula_docentes_id_fkey FOREIGN KEY (docentes_id)
    REFERENCES colegio.docentes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS colegio.matricula
    ADD CONSTRAINT matricula_estudiantes_id_fkey FOREIGN KEY (estudiantes_id)
    REFERENCES colegio.estudiantes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS colegio.matricula
    ADD CONSTRAINT matricula_materias_id_fkey FOREIGN KEY (materias_id)
    REFERENCES colegio.materias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS colegio.notas
    ADD FOREIGN KEY (materias_id)
    REFERENCES colegio.materias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;